python 2.plot_gaussian.py 0
python 2.plot_gaussian.py 0.05
python 2.plot_gaussian.py 0.1
python 2.plot_gaussian.py 0.5
python 2.plot_gaussian.py 1
python 2.plot_gaussian.py 2
python 2.plot_gaussian.py 3
python 2.plot_gaussian.py 4
python 2.plot_gaussian.py 5
python 2.plot_gaussian.py 6
python 2.plot_gaussian.py 7
python 2.plot_gaussian.py 8
python 2.plot_gaussian.py 9
python 2.plot_gaussian.py 10
